version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: rust_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rustuser
      POSTGRES_PASSWORD: rustpassword
      POSTGRES_DB: rustdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
